/*
 * App URI: app/example/AppManager
 * Source Location: app/example/AppManager.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/example/AppManager", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * AppManager.js
			 * Created at Oct 24, 2018 10:36:59 AM.
			 *
			 * @author ljy
			 ************************************************/
			
			function ofReady(params, direction) {
				console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
			
			}
			
			/**
			 * 앱 종료 콜백
			 * 
			 * @param ret
			 */
			onCloseCallback = function(ret) {
				if (ret.resultCode == "0") {
					alert("앱이 정상적으로 Close 되었습니다.");
				} else {
					alert("실패 : " + ret.errorMessage);
				}
			};
			
			/**
			 * 앱 서치 콜백
			 * 
			 * @param ret
			 */
			onSearchCallback = function(ret) {
				if (ret.resultCode == "0") {
					alert("Search가 정상적으로 작동 하였습니다.");
				} else {
					alert("실패 : " + ret.errorMessage);
				}
			};
			
			/**
			 * 앱 실행 콜백
			 * 
			 * @param ret
			 */
			onStartAppCallback = function(ret) {
				if (ret.resultCode == "0") {
					alert("정상적으로 시작 되었습니다.");
				} else {
					alert("실패 : " + ret.errorMessage);
				}
			};
			
			/**
			 * 웹 실행 콜백
			 * 
			 * @param ret
			 */
			onStartWebCallback = function(ret) {
				if (ret.resultCode == "0") {
					alert("정상적으로 시작 되었습니다.");
				} else {
					alert("실패 : " + ret.errorMessage);
				}
			};
			
			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				backPressed();
			}
			
			/*
			 * "앱종료" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnCloseClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnClose = e.control;
			
				var sendParam = {
					'type': 'finish'
				};
			
				OFPlugin.app.close(onCloseCallback, sendParam);
			}
			
			/*
			 * "앱 검색" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSearchClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSearch = e.control;
			
				var etPackage = app.lookup("etPackage");
			
				if (!etPackage.value) {
					alert("패키지명을 입력해 주세요");
					return;
				}
			
				var sendParam = {
					'ios': etPackage.value,
					'android': etPackage.value
				};
			
				OFPlugin.app.search(onSearchCallback, sendParam);
			}
			
			/*
			 * "앱 실행" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnExecuteClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnExecute = e.control;
			
				var etPackage = app.lookup("etPackage");
			
				if (!etPackage.value) {
					alert("패키지명을 입력해 주세요");
					return;
				}
			
				var sendParam = {
					'ios': etPackage.value,
					'android': etPackage.value
				};
			
				OFPlugin.app.start(onStartAppCallback, sendParam);
			}
			
			/*
			 * "웹 실행" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnWebClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnWeb = e.control;
			
				var etUrl = app.lookup("etUrl");
			
				if (!etUrl.value) {
					alert("URL을 입력해 주세요");
					return;
				}
			
				var sendParam = {
					'url': etUrl.value
				};
			
				OFPlugin.app.startWeb(onStartWebCallback, sendParam);
			}
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad( /* cpr.events.CEvent */ e) {
				setNowPage(app);
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "이전";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "10px",
				"left": "10px",
				"width": "79px",
				"height": "20px"
			});
			
			var button_2 = new cpr.controls.Button("btnClose");
			button_2.value = "앱종료";
			if(typeof onBtnCloseClick == "function") {
				button_2.addEventListener("click", onBtnCloseClick);
			}
			container.addChild(button_2, {
				"top": "256px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_3 = new cpr.controls.Button("btnSearch");
			button_3.value = "앱 검색";
			if(typeof onBtnSearchClick == "function") {
				button_3.addEventListener("click", onBtnSearchClick);
			}
			container.addChild(button_3, {
				"top": "79px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_4 = new cpr.controls.Button("btnExecute");
			button_4.value = "앱 실행";
			if(typeof onBtnExecuteClick == "function") {
				button_4.addEventListener("click", onBtnExecuteClick);
			}
			container.addChild(button_4, {
				"top": "109px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("etPackage");
			container.addChild(textArea_1, {
				"top": "43px",
				"left": "10px",
				"width": "251px",
				"height": "26px"
			});
			
			var button_5 = new cpr.controls.Button("btnWeb");
			button_5.value = "웹 실행";
			if(typeof onBtnWebClick == "function") {
				button_5.addEventListener("click", onBtnWebClick);
			}
			container.addChild(button_5, {
				"top": "175px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var textArea_2 = new cpr.controls.TextArea("etUrl");
			textArea_2.value = "http://";
			container.addChild(textArea_2, {
				"top": "139px",
				"left": "10px",
				"width": "251px",
				"height": "26px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "AppManager";
	cpr.core.Platform.INSTANCE.register(app);
})();
