/*
 * App URI: app/example/Cert
 * Source Location: app/example/Cert.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/example/Cert", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Cert.js
			 * Created at 2018. 12. 10. 오후 2:33:02.
			 *
			 * @author ljy
			 ************************************************/
			
			function ofReady(params, direction) {
				console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
			
			}
			
			onCertCenterCallback = function(result) {
				console.log("onCertCenterCallback = " + JSON.stringify(result));
			};
			
			onSignCallback = function(result) {
				alert("onSignCallback = " + JSON.stringify(result));
			};
			
			onVIDCheckCallback = function(result) {
				alert("onVIDCheckCallback = " + JSON.stringify(result));
			};
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad( /* cpr.events.CEvent */ e) {
				setNowPage(app);
			}
			
			/*
			 * "이전 1" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				backPressed();
			}
			
			/*
			 * "인증센터 실행요청" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnAuthCenterClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnAuthCenter = e.control;
			
				if (getUserAgent() != "else") {
					OFPlugin.cert.startCertCenter(onCertCenterCallback);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "사인요청" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSignClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSign = e.control;
			
				var param = {
					type: 1,
					value: "2222"
				};
			
				if (getUserAgent() != "else") {
					OFPlugin.cert.getSign(onSignCallback, param);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "본인인증요청" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnAuthClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnAuth = e.control;
			
				var param = {
					type: 1
				};
			
				if (getUserAgent() != "else") {
					OFPlugin.cert.getVIDCheck(onVIDCheckCallback, param);
				} else {
					alert("지원안함");
				}
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "이전 1";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "10px",
				"left": "10px",
				"width": "100px",
				"height": "20px"
			});
			
			var button_2 = new cpr.controls.Button("btnAuthCenter");
			button_2.value = "인증센터 실행요청";
			if(typeof onBtnAuthCenterClick == "function") {
				button_2.addEventListener("click", onBtnAuthCenterClick);
			}
			container.addChild(button_2, {
				"top": "51px",
				"left": "10px",
				"width": "208px",
				"height": "20px"
			});
			
			var button_3 = new cpr.controls.Button("btnSign");
			button_3.value = "사인요청";
			if(typeof onBtnSignClick == "function") {
				button_3.addEventListener("click", onBtnSignClick);
			}
			container.addChild(button_3, {
				"top": "81px",
				"left": "10px",
				"width": "208px",
				"height": "20px"
			});
			
			var button_4 = new cpr.controls.Button("btnAuth");
			button_4.value = "본인인증요청";
			if(typeof onBtnAuthClick == "function") {
				button_4.addEventListener("click", onBtnAuthClick);
			}
			container.addChild(button_4, {
				"top": "111px",
				"left": "10px",
				"width": "208px",
				"height": "20px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "Cert";
	cpr.core.Platform.INSTANCE.register(app);
})();
