/*
 * App URI: app/example/ClipBoard
 * Source Location: app/example/ClipBoard.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/example/ClipBoard", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * clipBoard.js
			 * Created at Oct 24, 2018 10:12:06 AM.
			 *
			 * @author ljy
			 ************************************************/
			
			function ofReady(params, direction) {
				console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
			
			}
			
			onSetClipBoardCallback = function(clipBoard) {
				if (clipBoard.resultCode == "0") {
					alert("정상적으로 저장 되었습니다.");
				} else {
					alert("실패 : " + clipBoard.errorMessage);
				}
			};
			
			onGetClipBoardCallback = function(clipBoard) {
				if (clipBoard.resultCode == "0") {
					alert("클립보드 : " + clipBoard.result);
				} else {
					alert("실패 : " + clipBoard.errorMessage);
				}
			};
			
			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				backPressed();
			}
			
			/*
			 * "setValue" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSetValueClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSetValue = e.control;
			
				var params = [];
			
				var etValue = app.lookup("etValue");
			
				if (!etValue.value) {
					alert("저장할 값을 입력해 주세요");
					return;
				}
			
				if (etValue.value) {
					params.push(etValue.value);
				}
			
				OFPlugin.clipboard.setText(onSetClipBoardCallback, params);
			}
			
			/*
			 * "getValue" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnGetValueClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnGetValue = e.control;
			
				OFPlugin.clipboard.getText(onGetClipBoardCallback);
			}
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad( /* cpr.events.CEvent */ e) {
				setNowPage(app);
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "이전";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "10px",
				"left": "20px",
				"width": "79px",
				"height": "20px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("etValue");
			container.addChild(textArea_1, {
				"top": "43px",
				"left": "20px",
				"width": "251px",
				"height": "82px"
			});
			
			var button_2 = new cpr.controls.Button("btnSetValue");
			button_2.value = "setValue";
			if(typeof onBtnSetValueClick == "function") {
				button_2.addEventListener("click", onBtnSetValueClick);
			}
			container.addChild(button_2, {
				"top": "136px",
				"left": "20px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_3 = new cpr.controls.Button("btnGetValue");
			button_3.value = "getValue";
			if(typeof onBtnGetValueClick == "function") {
				button_3.addEventListener("click", onBtnGetValueClick);
			}
			container.addChild(button_3, {
				"top": "173px",
				"left": "20px",
				"width": "251px",
				"height": "20px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "ClipBoard";
	cpr.core.Platform.INSTANCE.register(app);
})();
