/*
 * App URI: app/example/Navigator
 * Source Location: app/example/Navigator.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/example/Navigator", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * example2.js
			 * Created at Oct 23, 2018 4:47:59 PM.
			 *
			 * @author ljy
			 ************************************************/
			
			function ofReady(params, direction) {
				console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
			
			}
			
			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				backPressed();
			}
			
			/*
			 * "이동" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnGoClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnGo = e.control;
			
				var etId = app.lookup("etId");
			
				if (!etId.value) {
					alert("이동할 화면 ID를 입력해 주세요");
					return;
				}
			
				var param = {
					"historyId": etId.value,
					"classId": etId.value
				};
			
				param.nativeParameter = {};
				param.webParameter = {
					"sub": {
						"url": "http://192.168.42.131/sub.html"
					}
				};
			
				// "url": "http://192.168.42.131/index.html"
			
				alert(JSON.stringify(param));
			
				OFNavigator.go(param);
			}
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad( /* cpr.events.CEvent */ e) {
				setNowPage(app);
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "이전";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "10px",
				"left": "10px",
				"width": "79px",
				"height": "20px"
			});
			
			var inputBox_1 = new cpr.controls.InputBox("etId");
			inputBox_1.value = "sub";
			container.addChild(inputBox_1, {
				"top": "41px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var button_2 = new cpr.controls.Button("btnGo");
			button_2.value = "이동";
			if(typeof onBtnGoClick == "function") {
				button_2.addEventListener("click", onBtnGoClick);
			}
			container.addChild(button_2, {
				"top": "76px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "Navigator";
	cpr.core.Platform.INSTANCE.register(app);
})();
