/*
 * App URI: app/example/Sms
 * Source Location: app/example/Sms.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/example/Sms", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Sms.js
			 * Created at 2018. 12. 13. 오전 10:13:09.
			 *
			 * @author ljy
			 ************************************************/
			
			function ofReady(params, direction) {
				console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
			
			}
			
			onSmsCallback = function(result) {
				alert("onSmsCallback = " + JSON.stringify(result));
			};
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad( /* cpr.events.CEvent */ e) {
				setNowPage(app);
			}
			
			/*
			 * "이전" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
			
				backPressed();
			}
			
			/*
			 * "search" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSearchClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSearch = e.control;
			
				var etSearchPhonenum = app.lookup("etSearchPhonenum");
				var etText = app.lookup("etText");
				var etSearchStartDate = app.lookup("etSearchStartDate");
				var etSearchLastDate = app.lookup("etSearchLastDate");
			
				var startDate = etSearchStartDate.value;
				var lastDate = etSearchLastDate.value;
			
				if (!startDate || 0 === startDate.length) {
					startDate = "-1";
				}
				if (!lastDate || 0 === lastDate.length) {
					lastDate = "-1";
				}
			
				var param = {
					phonenum: etSearchPhonenum.value,
					text: etText.value,
					startDate: Number(startDate),
					lastDate: Number(lastDate)
				};
			
				if (getUserAgent() != "else") {
					OFPlugin.sms.search(onSmsCallback, param);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "sendSMS" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSendSMSClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSendSMS = e.control;
			
				var etSendPhonenum = app.lookup("etSendPhonenum");
				var etSendMessage = app.lookup("etSendMessage");
			
				var param = {
					phonenum: etSendPhonenum.value,
					message: etSendMessage.value
				};
			
				if (getUserAgent() != "else") {
					OFPlugin.sms.send(onSmsCallback, param);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "sendSMSUI" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnSendSMSUIClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnSendSMSUI = e.control;
			
				var etSendPhonenum = app.lookup("etSendPhonenum");
				var etSendMessage = app.lookup("etSendMessage");
			
				var param = {
					phonenum: etSendPhonenum.value,
					message: etSendMessage.value
				};
			
				if (getUserAgent() != "else") {
					OFPlugin.sms.sendUI(onSmsCallback, param);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "startSMSReceiver" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnStartSMSReceiverClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnStartSMSReceiver = e.control;
			
				if (getUserAgent() != "else") {
					OFPlugin.sms.startReceiver(onSmsCallback);
				} else {
					alert("지원안함");
				}
			}
			
			/*
			 * "stopSMSReceiver" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnStopSMSReceiverClick( /* cpr.events.CMouseEvent */ e) {
				/** 
				 * @type cpr.controls.Button
				 */
				var btnStopSMSReceiver = e.control;
			
				if (getUserAgent() != "else") {
					OFPlugin.sms.stopReceiver(onSmsCallback);
				} else {
					alert("지원안함");
				}
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "이전";
			if(typeof onButtonClick == "function") {
				button_1.addEventListener("click", onButtonClick);
			}
			container.addChild(button_1, {
				"top": "10px",
				"left": "10px",
				"width": "100px",
				"height": "20px"
			});
			
			var inputBox_1 = new cpr.controls.InputBox("etSearchPhonenum");
			inputBox_1.placeholder = "phonenum";
			inputBox_1.value = "";
			container.addChild(inputBox_1, {
				"top": "40px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var inputBox_2 = new cpr.controls.InputBox("etText");
			inputBox_2.placeholder = "text";
			inputBox_2.value = "";
			container.addChild(inputBox_2, {
				"top": "75px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var inputBox_3 = new cpr.controls.InputBox("etSearchStartDate");
			inputBox_3.placeholder = "startDate";
			inputBox_3.value = "";
			container.addChild(inputBox_3, {
				"top": "110px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var inputBox_4 = new cpr.controls.InputBox("etSearchLastDate");
			inputBox_4.placeholder = "lastDate";
			inputBox_4.value = "";
			container.addChild(inputBox_4, {
				"top": "145px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var button_2 = new cpr.controls.Button("btnSearch");
			button_2.value = "search";
			if(typeof onBtnSearchClick == "function") {
				button_2.addEventListener("click", onBtnSearchClick);
			}
			container.addChild(button_2, {
				"top": "180px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var inputBox_5 = new cpr.controls.InputBox("etSendPhonenum");
			inputBox_5.placeholder = "phonenum";
			inputBox_5.value = "";
			container.addChild(inputBox_5, {
				"top": "234px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var inputBox_6 = new cpr.controls.InputBox("etSendMessage");
			inputBox_6.placeholder = "message";
			inputBox_6.value = "";
			container.addChild(inputBox_6, {
				"top": "269px",
				"left": "10px",
				"width": "251px",
				"height": "25px"
			});
			
			var button_3 = new cpr.controls.Button("btnSendSMS");
			button_3.value = "sendSMS";
			if(typeof onBtnSendSMSClick == "function") {
				button_3.addEventListener("click", onBtnSendSMSClick);
			}
			container.addChild(button_3, {
				"top": "304px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_4 = new cpr.controls.Button("btnSendSMSUI");
			button_4.value = "sendSMSUI";
			if(typeof onBtnSendSMSUIClick == "function") {
				button_4.addEventListener("click", onBtnSendSMSUIClick);
			}
			container.addChild(button_4, {
				"top": "334px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_5 = new cpr.controls.Button("btnStopSMSReceiver");
			button_5.value = "stopSMSReceiver";
			if(typeof onBtnStopSMSReceiverClick == "function") {
				button_5.addEventListener("click", onBtnStopSMSReceiverClick);
			}
			container.addChild(button_5, {
				"top": "409px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			
			var button_6 = new cpr.controls.Button("btnStartSMSReceiver");
			button_6.value = "startSMSReceiver";
			if(typeof onBtnStartSMSReceiverClick == "function") {
				button_6.addEventListener("click", onBtnStartSMSReceiverClick);
			}
			container.addChild(button_6, {
				"top": "379px",
				"left": "10px",
				"width": "251px",
				"height": "20px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "Sms";
	cpr.core.Platform.INSTANCE.register(app);
})();
