/*
 * App URI: ScrollSnap
 * Source Location: ScrollSnap.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("ScrollSnap", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * ScrollSnap.js
			 * Created at 2019. 1. 14. 오후 6:09:49.
			 *
			 * @author jeeeyul
			 ************************************************/
			
			var edgeSpeed = 5;
			
			var _offsetY = -1;
			var _offsetScrollTop = -1;
			
			/** @type TouchEvent */
			var _lastKnownTouchMoveEvent;
			var _lastKnwonTouchMoveSpeed = 0;
			
			/**
			 * 
			 * @param {Boolean} preferUpperContent
			 */
			function snap(preferUpperContent) {
				var viewPortRect = app.getContainer().getViewPortRect();
				var children = app.getContainer().getChildren();
				/** @type cpr.controls.UIControl */
				var target = null;
				for (var idx = 0; idx < children.length && target == null; idx++) {
					if (viewPortRect.intersects(children[idx].getOffsetRect())) {
						target = children[idx];
					}
				}
			
				if (!preferUpperContent) {
					var idx = children.indexOf(target);
					target = children[idx + 1] || target;
				}
				if (target) {
					app.getContainer().scrollTo(0, target.getOffsetRect().y, 0.2, cpr.animation.TimingFunction.EASE_OUT);
				}
			}
			
			function startDrag(offsetY) {
				_offsetY = offsetY;
				_offsetScrollTop = app.getContainer().getViewPortRect().y;
			}
			
			/**
			 * 
			 * @param {Number} currentY
			 */
			function handleDrag(currentY) {
				var delta = _offsetY - currentY;
				var newScollTop = _offsetScrollTop + delta;
				app.getContainer().scrollTo(0, newScollTop);
			}
			
			/**
			 * 
			 * @param {MouseEvent} e
			 */
			function onMouseDown(e) {
				window.addEventListener("mousemove", onMouseMove);
				window.addEventListener("mouseup", onMouseUp);
				startDrag(e.screenY);
			}
			
			/**
			 * 
			 * @param {MouseEvent} e
			 */
			function onMouseMove(e) {
				handleDrag(e.screenY);
			}
			
			/**
			 * @param {MouseEvent} e
			 */
			function onMouseUp(e) {
				snap(e.screenY > _offsetY);
				window.removeEventListener("mousemove", onMouseMove);
				window.removeEventListener("mouseup", onMouseUp);
			}
			
			/**
			 * 
			 * @param {TouchEvent} e
			 */
			function onTouchStart(e) {
				window.addEventListener("touchmove", onTouchMove);
				window.addEventListener("touchend", onTouchEnd);
				console.log("start", e.timeStamp);
				startDrag(e.touches.item(0).screenY);
				e.preventDefault();
			}
			
			/**
			 * 
			 * @param {TouchEvent} e
			 */
			function onTouchMove(e) {
				handleDrag(e.touches.item(0).screenY);
				if (_lastKnownTouchMoveEvent) {
					var timeDelta = e.timeStamp - _lastKnownTouchMoveEvent.timeStamp;
					var yDelta = _lastKnownTouchMoveEvent.touches.item(0).screenY - e.touches.item(0).screenY;
					var speed = yDelta / timeDelta;
					if (Math.abs(speed) > Math.abs(_lastKnwonTouchMoveSpeed)) {
						_lastKnwonTouchMoveSpeed = speed;
					}
				}
				_lastKnownTouchMoveEvent = e;
			}
			
			/**
			 * @param {TouchEvent} e
			 */
			function onTouchEnd(e) {
				var container = app.getContainer();
				window.removeEventListener("touchmove", onTouchMove);
				window.removeEventListener("touchend", onTouchEnd);
				console.log(_lastKnwonTouchMoveSpeed);
			
				if (_lastKnwonTouchMoveSpeed < -edgeSpeed) {
					container.scrollTo(0, 0, 0.3);
				} else if (_lastKnwonTouchMoveSpeed > edgeSpeed) {
					var maxScrollTop = container.getContentPaneRect().height - container.getViewPortRect().height;
					container.scrollTo(0, maxScrollTop, 0.3);
				} else {
					snap(_lastKnwonTouchMoveSpeed < 0);
				}
			
				_lastKnownTouchMoveEvent = null;
				_lastKnwonTouchMoveSpeed = 0;
			
			}
			
			/*
			 * Body에서 init 이벤트 발생 시 호출.
			 * 앱이 최초 구성될 때 발생하는 이벤트 입니다.
			 */
			function onBodyInit( /* cpr.events.CEvent */ e) {
				app.getContainer().addEventListener("mousedown", onMouseDown);
				app.getContainer().addEventListener("touchstart", onTouchStart);
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1440px)", "default");
			app.supportMedia("all and (min-width: 800px) and (max-width: 1439px)", "tablet");
			app.supportMedia("all and (max-width: 799px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.scrollable = false;
			verticalLayout_1.spacing = 0;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#b34646",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 0;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "Card 1";
				output_1.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_1, {
					"width": "100px",
					"height": "40px"
				});
				var group_2 = new cpr.controls.Container();
				// Layout
				var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_3.horizontalMargin = 20;
				group_2.setLayout(verticalLayout_3);
				(function(container){
					var output_2 = new cpr.controls.Output();
					output_2.value = "스크롤 방향에 따라 가장 가까운 카드로 스내핑 됩니다.";
					output_2.style.css({
						"color" : "#fff"
					});
					container.addChild(output_2, {
						"width": "142px",
						"height": "28px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "400px",
					"height": "158px"
				});
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "200px"
			});
			
			var group_3 = new cpr.controls.Container();
			group_3.style.css({
				"background-color" : "#ffc32a",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_4.spacing = 0;
			group_3.setLayout(verticalLayout_4);
			(function(container){
				var output_3 = new cpr.controls.Output();
				output_3.value = "Card 2";
				output_3.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_3, {
					"width": "100px",
					"height": "40px"
				});
			})(group_3);
			container.addChild(group_3, {
				"width": "800px",
				"height": "300px"
			});
			
			var group_4 = new cpr.controls.Container();
			group_4.style.css({
				"background-color" : "#54cdc5",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_5.spacing = 0;
			group_4.setLayout(verticalLayout_5);
			(function(container){
				var output_4 = new cpr.controls.Output();
				output_4.value = "Card 3";
				output_4.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_4, {
					"width": "100px",
					"height": "40px"
				});
			})(group_4);
			container.addChild(group_4, {
				"width": "800px",
				"height": "200px"
			});
			
			var group_5 = new cpr.controls.Container();
			group_5.style.css({
				"background-color" : "#73a9d8",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_6.spacing = 0;
			group_5.setLayout(verticalLayout_6);
			(function(container){
				var output_5 = new cpr.controls.Output();
				output_5.value = "Card 4";
				output_5.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_5, {
					"width": "100px",
					"height": "40px"
				});
			})(group_5);
			container.addChild(group_5, {
				"width": "800px",
				"height": "500px"
			});
			
			var group_6 = new cpr.controls.Container();
			group_6.style.css({
				"background-color" : "#a65ec6",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_7.spacing = 0;
			group_6.setLayout(verticalLayout_7);
			(function(container){
				var output_6 = new cpr.controls.Output();
				output_6.value = "Card 5";
				output_6.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_6, {
					"width": "100px",
					"height": "40px"
				});
			})(group_6);
			container.addChild(group_6, {
				"width": "800px",
				"height": "200px"
			});
			
			var group_7 = new cpr.controls.Container();
			group_7.style.css({
				"background-color" : "#b84b93",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_8.spacing = 0;
			group_7.setLayout(verticalLayout_8);
			(function(container){
				var output_7 = new cpr.controls.Output();
				output_7.value = "Card 6";
				output_7.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_7, {
					"width": "100px",
					"height": "40px"
				});
			})(group_7);
			container.addChild(group_7, {
				"width": "800px",
				"height": "300px"
			});
			
			var group_8 = new cpr.controls.Container();
			group_8.style.css({
				"background-color" : "#ff4b00",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_9.spacing = 0;
			group_8.setLayout(verticalLayout_9);
			(function(container){
				var output_8 = new cpr.controls.Output();
				output_8.value = "Card 7";
				output_8.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_8, {
					"width": "100px",
					"height": "40px"
				});
			})(group_8);
			container.addChild(group_8, {
				"width": "800px",
				"height": "200px"
			});
			
			var group_9 = new cpr.controls.Container();
			group_9.style.css({
				"background-color" : "#7ecd41",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_10.spacing = 0;
			group_9.setLayout(verticalLayout_10);
			(function(container){
				var output_9 = new cpr.controls.Output();
				output_9.value = "Card 8";
				output_9.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_9, {
					"width": "100px",
					"height": "40px"
				});
			})(group_9);
			container.addChild(group_9, {
				"width": "800px",
				"height": "200px"
			});
			
			var group_10 = new cpr.controls.Container();
			group_10.style.css({
				"background-color" : "#c4daed",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_11.spacing = 0;
			group_10.setLayout(verticalLayout_11);
			(function(container){
				var output_10 = new cpr.controls.Output();
				output_10.value = "Card 9";
				output_10.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_10, {
					"width": "100px",
					"height": "40px"
				});
			})(group_10);
			container.addChild(group_10, {
				"width": "800px",
				"height": "200px"
			});
			
			var group_11 = new cpr.controls.Container();
			group_11.style.css({
				"background-color" : "#e052ac",
				"background-image" : "none"
			});
			// Layout
			var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_12.spacing = 0;
			group_11.setLayout(verticalLayout_12);
			(function(container){
				var output_11 = new cpr.controls.Output();
				output_11.value = "Card 10";
				output_11.style.css({
					"background-color" : "rgba(0, 0, 0, 0.3)",
					"padding" : "0px 0px 0px 20px",
					"color" : "white",
					"font-size" : "16pt"
				});
				container.addChild(output_11, {
					"width": "100px",
					"height": "40px"
				});
			})(group_11);
			container.addChild(group_11, {
				"width": "800px",
				"height": "400px"
			});
			if(typeof onBodyInit == "function"){
				app.addEventListener("init", onBodyInit);
			}
		}
	});
	app.title = "ScrollSnap";
	cpr.core.Platform.INSTANCE.register(app);
})();
/**
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
cpr.I18N.INSTANCE.setLocaleData("ko", {"gretting": "안녕하세요, eXbuilder6!"});
cpr.I18N.INSTANCE.setLocaleData("en", {"gretting": "Hello, eXbuilder6!"});
