/// start - mobil
/*
 * Module URI: mobil
 * SRC: mobil.module.js
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	cpr.core.Module.define("mobil", function(exports, globals, module){
		/************************************************
		 * mobil.module.js
		 * Created at 2018. 12. 31. 오후 3:09:10.
		 *
		 * @author hongkyukim
		 ************************************************/
		
		
		
			openBoxLoaded = function(){
						
						alert("openBoxLoaded ");
					};
					
					
		//	 function ofReady(params, direction) {
		//					
		//					  	alert(params);
		//					
		//		console.log("ofReady param = " + JSON.stringify(params, null, 4) + " / direction = " + direction);
		//				
		//		}			
					
		
		// 화면 로딩전 
		cpr.events.EventBus.INSTANCE.addFilter("init", function(e) {
			
			
			//alert("init");
			
			    OFHistory.list(function(result) {
		            if (result.resultCode == 0) {
		                var historyObject = result.result;
		                if (historyObject) {
		                    if(typeof ofReady != "undefined") {
		                        try{
		                     	
		                        ofReady(historyObject.list[historyObject.index], historyObject.direction);
		                        
		                        }catch(err){
		      
		        				}
		                        
		                        
		                    }
		                }
		            }
		        });
		        
		        
		       
			
			
		});
		
		
		
		
		
		// 화면 로딩후  
		cpr.events.EventBus.INSTANCE.addFilter("load", function(e) {
			
			// alert("load");
			 
		        OFHistory.list(function(result) {
		            if (result.resultCode == 0) {
		                var historyObject = result.result;
		                if (historyObject) {
		                    if(typeof ofReady != "undefined") {
		                        ofReady(historyObject.list[historyObject.index], historyObject.direction);
		                    }
		                }
		            }
		        });
			
			
			
			
			
		});
	});
})();
/// end - mobil
